### ISSUE TITLE
memeSendChannel.send(meme).catch(console.error);

### ISSUE THREAD

**Issue by jayaranah** [BlazeIsClone/A41SLBOT#13]
```
/A41SLBOT/src/events/guild/ready.js:32
      memeSendChannel.send(meme).catch(console.error);
                       ^

TypeError: Cannot read property 'send' of undefined
    at Request._callback (/A41SLBOT/src/events/guild/ready.js:32:23)
    at Request.self.callback (/A41SLBOT/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/A41SLBOT/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/A41SLBOT/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by BlazeIsClone** [comment]
@jayaranah did you update your config file with you're channel ID?
