### ISSUE TITLE
Error  Bot Connected to : D:\A41SLBOT-master\src\events\reaction_roles\load.js:27           .messages.fetch(message_id)

### ISSUE THREAD

**Issue by Arshdeepandcoder123** [BlazeIsClone/A41SLBOT#25]
D:\A41SLBOT-master>node index.js
Reaction Roles : Fetching messages
Logged in as XCODER123!
Discord.js API Ready! ⚡
MemesAPI ready
Bot Connected to :
D:\A41SLBOT-master\src\events\reaction_roles\load.js:27
          .messages.fetch(message_id)
          ^

TypeError: Cannot read properties of undefined (reading 'messages')
    at D:\A41SLBOT-master\src\events\reaction_roles\load.js:27:11
    at Client.<anonymous> (D:\A41SLBOT-master\src\events\reaction_roles\load.js:47:7)
    at Client.emit (node:events:532:35)
    at WebSocketManager.triggerClientReady (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (node:events:520:28)
    at WebSocketShard.checkReady (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at Object.module.exports [as READY] (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\handlers\READY.js:20:9)
    at WebSocketManager.handlePacket (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\A41SLBOT-master\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\A41SLBOT-master\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (D:\A41SLBOT-master\node_modules\ws\lib\websocket.js:833:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (D:\A41SLBOT-master\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (D:\A41SLBOT-master\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (D:\A41SLBOT-master\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (D:\A41SLBOT-master\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
Plz help me

**Comment by BlazeIsClone** [comment]
@Arshdeepandcoder123 make sure you modify [src/database/roles-reaction.json](https://github.com/BlazeIsClone/A41SLBOT/blob/master/src/database/roles-reaction.json) with your specific credentials. Also, does this error crash the bot?
